### ISSUE TITLE
NullPointerException in Record generation

### ISSUE THREAD

**Issue by tshoang** [eventB-Soton/Records#9]
The Record generator causes some NullPointerException. A part of the stack trace is available below.

!STACK 0
java.lang.NullPointerException
	at ac.soton.eventb.records.generator.rules.RecordRuleMachine.fire(RecordRuleMachine.java:79)
	at ac.soton.emf.translator.impl.Translator.traverseModel(Translator.java:436)
	at ac.soton.emf.translator.impl.Translator.traverseModel(Translator.java:444)
	at ac.soton.emf.translator.impl.Translator.doGenerate(Translator.java:366)
	at ac.soton.emf.translator.impl.Translator.translate(Translator.java:146)
	at ac.soton.emf.translator.impl.TranslateCommand.doExecute(TranslateCommand.java:82)

**Comment by tshoang** [comment]
The code use bit-wise `&`, i.e. 
    `if (r.getSubsets()!=null & r.getSubsets().getName()!=r.getName()) {`
It should be `&&` instead
    `if (r.getSubsets()!=null && r.getSubsets().getName()!=r.getName()) {`

**Comment by tshoang** [comment]
Fixed with Pull Request #10 (Fixed NPE exception in Records generator)
